# Generated by Django 5.1.3 on 2024-11-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='landlord',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.BooleanField(null=True),
        ),
    ]
