# Generated by Django 5.1.3 on 2024-11-13 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='poster_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(help_text='Landmark (location)', max_length=255)),
                ('site_link', models.URLField(help_text='Object page link (https://www.google.de/maps/', max_length=150, null=True, verbose_name='Link to page')),
                ('property_type', models.IntegerField(choices=[(0, 'Apartment'), (1, 'House'), (2, 'Studio')], default=0)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.FloatField(default=0.0)),
                ('number_of_reviews', models.IntegerField(default=0)),
                ('number_of_views', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False, null=True)),
                ('pets_allowed', models.BooleanField(default=False, null=True)),
                ('room_service', models.BooleanField(default=False, null=True)),
                ('all_time_reception', models.BooleanField(default=False, null=True)),
                ('wifi_included', models.BooleanField(default=False, null=True)),
                ('wheelchair_accessible', models.BooleanField(default=False, null=True)),
                ('pool', models.BooleanField(default=False, null=True)),
                ('non_smoking_rooms', models.BooleanField(default=False, null=True)),
                ('airport_shuttle', models.BooleanField(default=False, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
